package com.story.relay.service;

import com.story.relay.dto.ImageGenerationRequestDto;
import com.story.relay.dto.ImageGenerationResponseDto;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Duration;
import java.time.Instant;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
public class ImageGenerationAiClient {

    private final WebClient imageGenerationAiWebClient;
    private final S3UploadService s3UploadService;

    /**
     * Generate image via AI server and upload to S3
     */
    public ImageGenerationResponseDto generateImage(ImageGenerationRequestDto request) {
        log.info("Requesting image generation from AI server");
        log.debug("Request details: nodeText={}, situation={}, episodeTitle={}",
            request.getNodeText(), request.getSituation(), request.getEpisodeTitle());

        // TODO: AI 서버 개발 완료 시 실제 호출로 변경
        // 현재는 Mock 응답 반환
        return generateMockImage(request);

        // 실제 구현 (AI 서버 준비 시 주석 해제):
        /*
        byte[] imageBytes = imageGenerationAiWebClient.post()
            .uri("/generate-image")
            .bodyValue(request)
            .retrieve()
            .bodyToMono(byte[].class)
            .timeout(Duration.ofSeconds(30))
            .onErrorResume(e -> {
                log.error("AI server error during image generation: {}", e.getMessage(), e);
                return Mono.error(new RuntimeException("Image generation failed: " + e.getMessage()));
            })
            .block();

        if (imageBytes == null || imageBytes.length == 0) {
            throw new RuntimeException("No image data received from AI server");
        }

        log.info("Image generated by AI, size: {} bytes", imageBytes.length);

        String fileKey = "images/" + UUID.randomUUID().toString() + ".png";
        String imageUrl = s3UploadService.uploadImage(fileKey, imageBytes);

        return ImageGenerationResponseDto.builder()
            .imageUrl(imageUrl)
            .fileKey(fileKey)
            .generatedAt(Instant.now().toString())
            .build();
        */
    }

    /**
     * Mock image generation (for testing before AI server is ready)
     */
    private ImageGenerationResponseDto generateMockImage(ImageGenerationRequestDto request) {
        log.warn("Using MOCK image generation (AI server not ready)");

        // Placeholder image URL
        String mockImageUrl = "https://via.placeholder.com/800x600/1a1a1a/ffffff?text=" +
            request.getEpisodeTitle().replaceAll(" ", "+");

        return ImageGenerationResponseDto.builder()
            .imageUrl(mockImageUrl)
            .fileKey("mock/image_" + UUID.randomUUID().toString() + ".png")
            .generatedAt(Instant.now().toString())
            .build();
    }

    /**
     * Check if image generation AI server is healthy
     */
    public boolean checkHealth() {
        try {
            // TODO: 실제 health check 엔드포인트 호출
            log.debug("Image generation AI health check (mock)");
            return true; // Mock: always healthy
        } catch (Exception e) {
            log.warn("Image generation AI health check failed: {}", e.getMessage());
            return false;
        }
    }
}
